/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'michaldolas' at '2/1/17 10:41 AM' with Gradle 3.0
 *
 * @author michaldolas, @date 2/1/17 10:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
